from views.aeroporto_view import *
from views.voo_view import *
from views.trecho_voo_view import *
from views.tarifa_view import *
from views.tipo_aeronave_view import *
from views.aeronave_view import *
from views.pode_pousar_view import *
from views.index_view import *
from views.busca_assento_view import *
from views.reserva_assento_view import *
from views.index_view import *
